"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { SiteHeader } from "../components/site-header";
export default function Join(){
 const [fullName,setFullName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [loading,setLoading]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setMessage(null);setError(null);try{if(password.length<8)throw new Error("Password must be at least 8 characters.");const supabase=createClient();const {data,error:signUpError}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/auth/callback`,data:{full_name:fullName,account_type:"candidate"}}});if(signUpError)throw signUpError;if(data.session){window.location.assign("/dashboard/profile");return;}setMessage("Account created. Check your email to verify your address, then sign in.");}catch(err){setError(err instanceof Error?err.message:"Unable to create your account.");}finally{setLoading(false);}}
 return <main><SiteHeader/><section className="company-hero"><div className="container company-hero__grid"><div><span className="eyebrow">FOR CANDIDATES</span><h1>Build a professional profile that goes beyond the résumé.</h1><p>Keep your information private, describe your strengths clearly and let Avenlo help surface relevant opportunities.</p><div className="company-hero__points"><span>✓ Private professional profile</span><span>✓ Structured skills & experience</span><span>✓ Human-led opportunities</span></div></div><div className="inquiry-card"><span className="eyebrow">CREATE YOUR PROFILE</span><h2>Join Avenlo.</h2><p>Candidate accounts are for people who want to build their professional profile and discover relevant opportunities.</p><form className="form" onSubmit={submit}><label>Full name<input required autoComplete="name" value={fullName} onChange={e=>setFullName(e.target.value)}/></label><label>Email<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input required type="password" minLength={8} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error?<p className="error" role="alert">{error}</p>:null}{message?<p className="muted" role="status">{message}</p>:null}<button className="btn btn--primary" type="submit" disabled={loading}>{loading?"Creating account…":"Create candidate profile →"}</button><p className="form-note">Already have an account? <Link href="/login">Sign in</Link></p></form></div></div></section></main>;
}
