import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import styles from "../tools.module.css";

const skillGroups: Record<string, string[]> = { "Product & strategy": ["product", "roadmap", "strategy", "analytics", "research", "sql", "figma", "stakeholder"], "Engineering & data": ["javascript", "typescript", "react", "next", "node", "python", "java", "sql", "aws", "docker", "data", "machine learning", "git"], "Business & operations": ["sales", "crm", "operations", "excel", "finance", "marketing", "project management", "communication"], "Design & creative": ["figma", "ux", "ui", "design", "photoshop", "illustrator", "research", "branding"] };
const developmentMap: Record<string, string[]> = { "Product & strategy": ["SQL", "product analytics", "user research", "stakeholder management"], "Engineering & data": ["testing", "cloud fundamentals", "system design", "data structures"], "Business & operations": ["advanced Excel", "data analysis", "process design", "CRM"], "Design & creative": ["UX research", "design systems", "accessibility", "prototyping"] };

export default async function SkillsCheckerPage() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const [{ data: skills }, { data: candidate }] = await Promise.all([supabase.from("candidate_skills").select("skill").eq("user_id", user.id).order("skill"), supabase.from("candidate_profiles").select("industry, seniority, preferences").eq("user_id", user.id).maybeSingle()]);
  const names = (skills ?? []).map((item) => item.skill.toLowerCase());
  const groups = Object.entries(skillGroups).map(([name, keywords]) => ({ name, count: names.filter((skill) => keywords.some((keyword) => skill.includes(keyword))).length })).sort((a, b) => b.count - a.count);
  const strongest = groups[0]; const development = strongest ? developmentMap[strongest.name].filter((item) => !names.some((skill) => skill.includes(item.toLowerCase()))).slice(0, 3) : ["Add your core skills", "Choose a target direction", "Add recent experience"];
  const coverage = Math.min(100, Math.round((names.length / 10) * 100));
  return <main className={styles.page}><nav className={styles.nav}><Link href="/dashboard"><span className="brand-lockup brand-lockup--compact"><span className="brand-copy"><span className="brand-wordmark">AVENLO</span></span></span></Link><div className={styles.navLinks}><Link href="/dashboard">Overview</Link><Link href="/dashboard/resume">Resume</Link><Link href="/dashboard/courses">Courses</Link><Link href="/dashboard/profile">Profile</Link></div></nav>
    <div className={styles.container}><Link className={styles.back} href="/dashboard">← Back to dashboard</Link><header className={styles.header}><div><span className={styles.eyebrow}>SKILLS CHECKER</span><h1>Understand your skill signal.</h1><p>Avenlo groups the skills on your profile, shows where your current strength sits and highlights a small number of useful development areas.</p></div></header>
      <div className={styles.grid}><section className={styles.card}><h2>Current coverage</h2><div className={styles.score} style={{ ["--score" as string]: `${coverage * 3.6}deg` }}><strong>{coverage}%</strong><span>PROFILE DEPTH</span></div><div className={styles.metricList}><div className={styles.metric}><span>Skills on file</span><strong>{names.length}</strong></div><div className={styles.metric}><span>Primary cluster</span><strong>{strongest?.name ?? "Not enough data"}</strong></div><div className={styles.metric}><span>Career context</span><strong>{candidate?.industry || "Add industry"}</strong></div></div></section>
        <section className={styles.card}><h2>Your strongest areas</h2><div className={styles.list}>{groups.slice(0, 4).map((group) => <div className={styles.item} key={group.name}><div className={styles.itemTop}><h3>{group.name}</h3><span className={styles.pill}>{group.count} signals</span></div><div className={styles.progressRow}><div className={styles.progressRowTop}><span>Coverage</span><span>{Math.min(100, group.count * 20)}%</span></div><div className={styles.bar}><span style={{ width: `${Math.min(100, group.count * 20)}%` }} /></div></div></div>)}</div></section></div>
      <div className={styles.grid} style={{ marginTop: 16 }}><section className={styles.card}><h2>Skills on your profile</h2>{names.length ? <div className={styles.list}>{names.map((skill) => <div className={styles.item} key={skill}><div className={styles.itemTop}><h3>{skill}</h3><span className={styles.pill}>On file</span></div></div>)}</div> : <p>No skills are recorded yet. Add them from your profile.</p>}<div className={styles.actions}><Link className="btn btn--primary btn--small" href="/dashboard/profile">Update skills</Link></div></section>
        <section className={styles.card}><h2>Useful next skills</h2><p>These are development prompts based on your strongest current cluster — not a mandatory course list.</p><div className={styles.checkList}>{development.map((item) => <div className={styles.checkItem} key={item}><span className={styles.checkIcon}>+</span><div><strong>{item}</strong><span>Consider building evidence for this skill through a project, course or real work.</span></div></div>)}</div><div className={styles.actions}><Link className="btn btn--small" href="/dashboard/courses">See course guidance</Link></div></section></div>
    </div></main>;
}
