import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import styles from "../tools.module.css";

export default async function RecommendationsPage() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const [{ data: profile }, { data: candidate }, { data: skills }] = await Promise.all([supabase.from("profiles").select("full_name, headline, location").eq("id", user.id).maybeSingle(), supabase.from("candidate_profiles").select("industry, seniority, work_mode, preferences").eq("user_id", user.id).maybeSingle(), supabase.from("candidate_skills").select("skill").eq("user_id", user.id)]);
  const roles = Array.isArray(candidate?.preferences?.target_roles) ? candidate.preferences.target_roles : []; const skillCount = skills?.length ?? 0; const profileReady = Boolean(profile?.full_name && profile?.headline && candidate?.industry && skillCount >= 3);
  return <main className={styles.page}><nav className={styles.nav}><Link href="/dashboard"><span className="brand-lockup brand-lockup--compact"><span className="brand-copy"><span className="brand-wordmark">AVENLO</span></span></span></Link><div className={styles.navLinks}><Link href="/dashboard">Overview</Link><Link href="/dashboard/resume">Resume</Link><Link href="/dashboard/skills">Skills</Link><Link href="/dashboard/profile">Profile</Link></div></nav>
    <div className={styles.container}><Link className={styles.back} href="/dashboard">← Back to dashboard</Link><header className={styles.header}><div><span className={styles.eyebrow}>RECOMMENDATION WORKFLOW</span><h1>We find the right next step for you.</h1><p>Avenlo is deliberately not a job board. You build the signal once, our team uses it to identify relevant opportunities, and we guide you when there is a strong fit.</p></div></header>
      <div className={styles.list}><article className={styles.item}><div className={styles.itemTop}><div><h3>01 · Understand</h3><p>We review your profile, resume, skills, education, experience and career direction.</p></div><span className={styles.pill}>{profileReady ? "Ready" : "Build signal"}</span></div></article><article className={styles.item}><div className={styles.itemTop}><div><h3>02 · Recommend</h3><p>Avenlo identifies relevant opportunities and learning actions based on fit — not a list of every available job.</p></div><span className={styles.pill}>Human-led</span></div></article><article className={styles.item}><div className={styles.itemTop}><div><h3>03 · Connect</h3><p>When a strong match appears, Avenlo guides the next conversation or action with you.</p></div><span className={styles.pill}>With you</span></div></article></div>
      <div className={styles.grid} style={{ marginTop: 16 }}><section className={styles.card}><h2>Your matching signal</h2><div className={styles.metricList}><div className={styles.metric}><span>Profile name</span><strong>{profile?.full_name ? "Ready" : "Add"}</strong></div><div className={styles.metric}><span>Career direction</span><strong>{candidate?.industry || "Add industry"}</strong></div><div className={styles.metric}><span>Skills</span><strong>{skillCount >= 3 ? `${skillCount} on file` : "Add 3+"}</strong></div><div className={styles.metric}><span>Preferred mode</span><strong>{candidate?.work_mode || "Add"}</strong></div><div className={styles.metric}><span>Target roles</span><strong>{roles.length ? `${roles.length} added` : "Add in profile"}</strong></div></div><div className={styles.actions}><Link className="btn btn--primary btn--small" href="/dashboard/profile">Update matching signal</Link></div></section><section className={styles.card}><h2>No hunting required</h2><p>You will not see a feed of jobs to scroll through here. The candidate experience is designed around better recommendations and fewer, more relevant decisions.</p><div className={styles.notice}>When Avenlo has a recommendation to discuss, the operations team can take the next step with you.</div></section></div>
    </div></main>;
}
