-- Do not expose the generic audit writer through the Supabase Data API.
-- Audit rows are generated by trusted database triggers instead.
revoke execute on function public.write_audit_log(text, text, uuid, jsonb) from public;
revoke execute on function public.write_audit_log(text, text, uuid, jsonb) from anon;
revoke execute on function public.write_audit_log(text, text, uuid, jsonb) from authenticated;
drop function if exists public.write_audit_log(text, text, uuid, jsonb);
